// Re-exporta todos los tipos del cliente HTTP
// Los tipos del dominio viven en src/services/axios.ts
// derivados del openapi.yaml
export type {
  ApiResponse,
  PaginatedResponse,
  Usuario,
  LoginCredentials,
  LoginResponse,
  Rol,
  ActorCooperacion,
  TipoActor,
  EstadoActor,
  CreateActorDto,
  UpdateActorDto,
  Proyecto,
  EstadoProyecto,
  FlujoDireccion,
  ModalidadCooperacion,
  ProvinciaProyecto,
  UbicacionProyecto,
  OdsResumen,
  CreateProyectoDto,
  UpdateProyectoDto,
  HitoProyecto,
  CreateHitoDto,
  BuenaPractica,
  ValoracionPractica,
  Red,
  TipoRed,
  MiembroRed,
  ProyectoEmblematico,
  Reconocimiento,
  CategoriaDocumento,
  EntidadDocumento,
  DocumentoItem,
  Evento,
  TipoEvento,
  CompromisoEvento,
  Provincia,
  Ods,
  UsuarioAdmin,
  RegistroAuditoria,
} from '@/services/axios';
